name: OpenHarmony Build

on:
  push:
    branches:
      - 'oh_**'
  pull_request:
    branches:
      - 'oh_**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run build script
      run: |
        chmod +x ./build-openharmony-x64.sh
        ./build-openharmony-x64.sh
